Kontent-ai-Learn/kontent-ai-learn-code-samples

- net/delivery-api/GetItemsFeed.cs
- rest/delivery-api/GetItemsFeed.curl
Prepare samples for new /items-feed endpoint in Delivery API.
> CTC-644 Add samples for API Reference of ItemsFeed

- net/strongly-typed-models/GenerateModels.sh
relates to https://github.com/Kentico/kontent-generators-net/releases/tag/4.1.0
> adjustment for generator 4.1.0 and above

- net/retrieving-linked-content/AuthorModel.cs
- net/retrieving-linked-content/SimpleArticleModel.cs
- net/strongly-typed-models/ModelDefinition.cs
- net/structure-in-rte/BlockquoteModel.cs
- net/structure-in-rte/TweetModel.cs
https://github.com/Kentico/kontent-generators-net/releases/tag/5.0.0-beta2
> Changes related to generator v5

- rest/importing-content-model/CreateSnippet.curl
Which issue does this fix? Fixes #`issue number`
If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?
> changed // to #

- rest/importing-content-model/CreateType.curl
Which issue does this fix? Fixes #`issue number`
If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?
> updated ID and changed // to #

- js/importing-content-model/CreateType.js
Which issue does this fix? Fixes #`issue number`
If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?
> updated DocSection ID

- net/management-api-v2/PatchContentCollections.cs
- net/management-api-v2/PutVariantUnpublishAndArchive.cs
Internal link: CTC-1467
* Add forgotten operation
* Adjust comment
Related to https://github.com/Kentico/kontent-management-sdk-net/pull/116
> Net sample fix

- net/management-api-v2/GetRole.cs
- net/management-api-v2/GetRoles.cs
- net/management-api-v2/PostUser.cs
- net/management-api-v2/PutUser.cs
New functionality related to:
* https://github.com/Kentico/kontent-management-sdk-net/issues/119
* https://github.com/Kentico/kontent-management-sdk-net/issues/120
> Add project endpoints .net MAPI code samples

- net/management-api-v2/GetProjectInformation.cs
- net/management-api-v2/GetSubscriptionUser.cs
- net/management-api-v2/GetSubscriptionUsers.cs
- net/management-api-v2/ListSubscrptionProjects.cs
- net/management-api-v2/PutSubscriptionUserActivate.cs
- net/management-api-v2/PutSubscriptionUserDeactivate.cs
- net/management-api-v2/PutVariantCancelSchedule.cs
- net/management-api-v2/PutVariantCancelScheduledUnpublish.cs
- net/management-api-v2/PutVariantCreateNewVersion.cs
- net/management-api-v2/PutVariantPublishOrSchedule.cs
- net/management-api-v2/PutVariantUnpublishAndArchive.cs
- net/management-api-v2/PutVariantWorkflow.cs
See:
* https://github.com/Kentico/kontent-management-sdk-net/pull/133
* https://github.com/Kentico/kontent-management-sdk-net/pull/141
> Subscription endpoints -  dotnet

- rest/management-api-v2/PatchEnvironment.curl
- rest/management-api-v2/PostEnvironmentClone.curl
Fixes REST code samples for KCP-3090
> KCP-3090 - fix environment MAPI REST samples

- net/management-api-v2/DeleteEnvironment.cs
- net/management-api-v2/GetEnvironmentCloningState.cs
- net/management-api-v2/PatchEnvironment.cs
- net/management-api-v2/PostEnvironmentClone.cs
- net/management-api-v2/PostEnvironmentMarkAsProduction.cs
Fixes KCP-3090 - Adds .NET code samples for environment MAPI
> KCP-3090 - add .NET code samples for environment MAPI

- js/management-api-v2/DeleteEnvironment.js
- js/management-api-v2/GetEnvironmentCloneStatus.js
- js/management-api-v2/PatchEnvironment.js
- js/management-api-v2/PostEnvironmentClone.js
- js/management-api-v2/PutEnvironmentMarkAsProduction.js
- rest/management-api-v2/PatchProject.curl
Fixes KCP-3090 - Adds js code samples for environment MAPI
> KCP-3090 - Add js samples for environment MAPI

- js/management-api-v2/PostAsset.js
- js/management-api-v2/PutAsset.js
- net/management-api-v2/PostAsset.cs
- net/management-api-v2/PutAsset.cs
- rest/management-api-v2/PostAsset.curl
- rest/management-api-v2/PutAsset.curl
Fixes CTC-1536 - Add elements property to the post and put asset code samples.
> CTC-1536 - Update asset code samples to include elements property

- net/management-api-v2/GetValidationIssues.cs
- net/management-api-v2/GetValidationTask.cs
- net/management-api-v2/PostValidateAsync.cs
New endpoints for async validation of the project have been added. Here are .NET code samples.
Add the following information:
* SDK changes are already out, so this can be released ASAP
* Is the pull request complete and ready for review?  Yes
> Add code samples for new validation endpoints

- java/delivery-api/GetElement.java
- java/delivery-api/GetItem.java
- java/delivery-api/GetItemPreview.java
- java/delivery-api/GetItems.java
- java/delivery-api/GetTaxonomyGroup.java
- java/delivery-api/GetTaxonomyGroups.java
- java/delivery-api/GetType.java
- java/delivery-api/GetTypes.java
- java/get-content/FilterItems.java
- java/get-content/GetItems.java
- java/get-content/OrderItems.java
- java/get-localized-content/GetLocalizedItems.java
- java/get-localized-content/GetLocalizedItemsWithSlug.java
- java/get-localized-content/IgnoreFallback.java
- java/manage-navigation/GetArticlesSlug.java
- java/preview-content/GetArticle.java
- java/retrieve-linked-content/AuthorModel.java
- java/retrieve-linked-content/GetPageWithSubpages.java
- java/retrieve-linked-content/GetSimpleArticleWithAuthor.java
- java/retrieve-linked-content/SimpleArticleModel.java
- java/secure-public-access/GetArticle.java
- java/share-project-content/GetItems.java
- java/strongly-typed-models/GenerateModels.java
- java/strongly-typed-models/GetTypedContent.java
- java/strongly-typed-models/ModelDefinition.java
- java/structure-in-rte/BlockquoteModel.java
- java/structure-in-rte/TweetModel.java
- java/use-webhooks/GetLatestContent.java
- java/use-webhooks/NotificationModel.java
DEVREL-662 - fix java API examples
Add the following information:
* When do you need the code to go public? Provide a release date and/or explanation.
* ASAP - new version is published
* Is the pull request complete and ready for review? **Yes**
> New java SDK version - API examples

- net/management-api-v2/DeleteSpace.cs
- net/management-api-v2/GetPreviewConfiguration.cs
- net/management-api-v2/GetSpace.cs
- net/management-api-v2/GetSpaces.cs
- net/management-api-v2/PatchSpace.cs
- net/management-api-v2/PostSpace.cs
- net/management-api-v2/PutPreviewConfiguration.cs
- rest/management-api-v2/DeleteSpace.curl
- rest/management-api-v2/GetPreviewConfiguration.curl
- rest/management-api-v2/GetSpace.curl
- rest/management-api-v2/GetSpaces.curl
- rest/management-api-v2/PatchSpace.curl
- rest/management-api-v2/PostSpace.curl
- rest/management-api-v2/PutPreviewConfiguration.curl
Adds curl and .net code samples for Spaces and Preview configuration
[Jira task](https://kontent-ai.atlassian.net/browse/KCL-9993)
[Spaces SDK PR](https://github.com/kontent-ai/management-sdk-net/pull/221)
[Preview SDK PR](https://github.com/kontent-ai/management-sdk-net/pull/218)
Release date: 2.2.
Ready to review: Yes
> Add code samples for spaces and preview

- net/management-api-v2/PostSpace.cs
* Brief description: The code sample was not correct
* GitHub or Jira issue URL: you can check the implementation https://github.com/kontent-ai/management-sdk-net/pull/221/files#diff-3226d39fdbe45d0089eb9fb9f5a047413cd84e6331bec3c867c18726b9a21c58R18
* When do you need the code to go public? Release date is 1.2.2023 (today)
* If this is a placeholder and you plan further changes, [set the pull request as draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests).
> Fix sample for creating a space in .NET SDK

- js/management-api-v2/PostWorkflow.js
- js/management-api-v2/PutWorkflow.js
- net/management-api-v2/PostWorkflow.cs
- net/management-api-v2/PutWorkflow.cs
- rest/management-api-v2/PostWorkflow.curl
- rest/management-api-v2/PutWorkflow.curl
This PR extends the existing sample requests for workflows in management api with the newly added collection restriction fields.
> CTC-1916 Collection limitations for PutWorkflow and PostWorkflow

- net/management-api-v2/PatchSpace.cs
- net/management-api-v2/PostSpace.cs
- net/management-api-v2/PutPreviewConfiguration.cs
- rest/management-api-v2/PatchSpace.curl
- rest/management-api-v2/PostSpace.curl
* Brief description: I've extended Spaces .net and cURL code samples with a new property. I've also fixed some issues in Space and Preview configuration code samples. 
JS code samples will be added later in a separate PR by NicholasM
* Jira issue URL: https://kontent-ai.atlassian.net/browse/CTC-1945
> CTC-1945 Add Spaces root item code samples 

- net/management-api-v2/PostAsset.cs
- net/management-api-v2/PutAsset.cs
- rest/management-api-v2/PostAsset.curl
- rest/management-api-v2/PutAsset.curl
* Brief description: Added collection property to asset .NET and cURL codesamples (no JS samples as JS SDK changes are not ready yet)
* GitHub or Jira issue URL: https://kontent-ai.atlassian.net/browse/CTC-2138
* When do you need the code to go public? On 19.9. (public release)
> Add Assets in collections codesamples

- net/management-api-v2/cm_api_v2_delete_legacy_webhook.cs
- net/management-api-v2/cm_api_v2_get_legacy_webhook.cs
- net/management-api-v2/cm_api_v2_get_legacy_webhooks.cs
- net/management-api-v2/cm_api_v2_post_legacy_webhook.cs
- net/management-api-v2/cm_api_v2_post_webhook.cs
- net/management-api-v2/mapi_v2_disable_legacy_webhook.cs
- net/management-api-v2/mapi_v2_enable_legacy_webhook.cs
Add new webhooks MAPI net code samples 
https://kontent-ai.atlassian.net/jira/software/c/projects/DEL/boards/501?selectedIssue=DEL-4734
> DEL-4734 - Add MAPI code samples for webhooks

- js/management-api-v2/cm_api_v2_get_variants_by_collection.js
- net/management-api-v2/cm_api_v2_get_variants_by_collection.cs
- net/management-api-v2/cm_api_v2_get_variants_by_space.cs
- net/management-api-v2/cm_api_v2_patch_space.cs
- net/management-api-v2/cm_api_v2_post_space.cs
- rest/management-api-v2/cm_api_v2_get_variants_by_space.curl
- rest/management-api-v2/cm_api_v2_patch_space.curl
- rest/management-api-v2/cm_api_v2_post_space.curl
* Brief description: I added code samples to reflect the SDK updates made in https://github.com/kontent-ai/management-sdk-net/pull/256
* GitHub or Jira issue URL: KCL-11869
* When do you need the code to go public? 29.1.2024
> Spaces and collections samples

- net/management-api-v2/cm_api_v2_post_webhook.cs
* Brief description: Enable customers to enhance webhook notifications with custom headers.
* GitHub or Jira issue URL: 
https://kontent-ai.atlassian.net/jira/software/c/projects/DEL/boards/501?selectedIssue=EN-44
https://github.com/kontent-ai/management-sdk-net/pull/258
* When do you need the code to go public? Provide a release date such as Jan 23, 2023, and/or explanation.
Do not release before Feb 21, 2024
> Add custom headers to webhooks

- net/management-api-v2/cm_api_v2_clone_environment.cs
- rest/management-api-v2/cm_api_v2_clone_environment.curl
* Brief description: Making cloning environment configurable - adding copy data options to select entities which should be copied
* GitHub or Jira issue URL: https://kontent-ai.atlassian.net/browse/CTC-2461
* When do you need the code to go public? May 30, 2024
> EN-199 Add copy data options to clone environment

- net/management-api-v2/GetWebSpotlightStatus.cs
- net/management-api-v2/PutWebSpotlightActivate.cs
- net/management-api-v2/PutWebSpotlightDeactivate.cs
Add samples for newly added Management API support of Web Spotlight
> CTC-2504 Add WebSpotlight samples

- js/management-api-v2/cm_api_v2_patch_asset_folders.js
- js/management-api-v2/cm_api_v2_post_asset_folders.js
- net/management-api-v2/cm_api_v2_patch_asset_folders.cs
- net/management-api-v2/cm_api_v2_post_asset_folders.cs
- rest/management-api-v2/cm_api_v2_patch_asset_folders.curl
- rest/management-api-v2/cm_api_v2_post_asset_folders.curl
* Brief description: We are allowing codenames as a reference for asset folders
* GitHub or Jira issue URL: https://kontent-ai.atlassian.net/browse/CTC-2534
* When do you need the code to go public? Change is already in API, SDKs are in progress, contact Risa and Daniel for more info
> EN-207 Add codenames to asset folders

- net/management-api-v2/cm_api_v2_delete_custom_app.cs
- net/management-api-v2/cm_api_v2_get_custom_app.cs
- net/management-api-v2/cm_api_v2_get_custom_apps.cs
- net/management-api-v2/cm_api_v2_patch_modify_custom_app.cs
- net/management-api-v2/cm_api_v2_post_create_custom_app.cs
* Code samples for new feature Custom Apps
* https://kontent-ai.atlassian.net/browse/EN-326
> EN-326 Add custom apps code samples

- ts/resolve-rich-text/resolve_rich_text_components_items.tsx
- ts/resolve-rich-text/resolve_rich_text_flow.tsx
- ts/resolve-rich-text/resolve_rich_text_links_to_items.tsx
* Brief description: Code samples update for TS rich text resolution, for upcoming release of [rich-text-resolver 2.0.0](https://github.com/kontent-ai/rich-text-resolver-js/tree/main)
* [DEVREL-1222](https://kontent-ai.atlassian.net/browse/DEVREL-1222)
* The sooner this is reviewed and merged, the better. Please contact devrel to sync merge with NPM release.
> update TS rich text resolution

- rest/management-api-v2/mapi_v2_get_live_preview_status.curl
- rest/management-api-v2/mapi_v2_put_live_preview_status.curl
* Brief description: I have added code samples for MAPIv2 REST endpoints for dynamic preview configuration
* GitHub or Jira issue URL: https://kontent-ai.atlassian.net/browse/CTC-2661 https://kontent-ai.atlassian.net/browse/CTC-2736
* When do you need the code to go public? 17.3.
> CTC-2661: Add rest code samples for Live preview endpoints

- net/delivery-api/delivery_api_get_asset_used_in.cs
- net/delivery-api/delivery_api_get_item_used_in.cs
- rest/delivery-api/delivery_api_get_asset_used_in.curl
- rest/delivery-api/delivery_api_get_item_used_in.curl
- ts/delivery-api/delivery_api_get_asset_used_in.ts
- ts/delivery-api/delivery_api_get_item_used_in.ts
* Brief description: introduced code samples for used in endpoints
* GitHub or Jira issue URL: [https://kontent-ai.atlassian.net/browse/EN-434](https://kontent-ai.atlassian.net/browse/EN-434)
* When do you need the code to go public? TBA.
> introduce code samples for used in endpoints

- ts/management-api-v2/cm_api_v2_filter_variants.ts
The JS SDK has not yet been released.
> Adds example for variant filtering in MAPI & JS SDK
